### ISSUE TITLE
Can OpenUPF run on Ubuntu？

### ISSUE THREAD

**Issue by 784432821** [5GOpenUPF/openupf#1]
Can openupf be compiled and run directly on Ubuntu system besides CentOS system? Will it be considered later?

**Comment by 5GOpenUPF** [comment]
Hi
Temporarily not supported, may consider later

**Comment by hrkgarg** [comment]
I have compiled the code on RHEL-8.8. However, when I am trying to run using start_upf.sh script, It is pulling the docker image for air5005/upu instead of taking the compiled code and creating redhat image from it. Please let me know how can I run UPF on Redhat-8
