### ISSUE TITLE
Docker Build Documentation

### ISSUE THREAD

**Issue by infinitydon** [5GOpenUPF/openupf#3]
Hi,

I am currently trying to build the docker image but I am getting the following errors:

```
$ sudo docker cp install/bin/ ${OPENUPF_IMAGE_NAME}:/opt/upf/bin
lstat /home/ec2-user/openupf/install/bin: no such file or directory
$ sudo docker cp install/lib/ ${OPENUPF_IMAGE_NAME}:/opt/upf/lib
lstat /home/ec2-user/openupf/install/lib: no such file or directory

$ ls
build  CMakeLists.txt  config  core  doc  images  install  libs  LICENSE  README.md
.
.
$ ls install/
script
```

There is no **_bin or lib_** in the install folder.

**Comment by infinitydon** [comment]
Image build works now, I missed the build step..

**Comment by hrkgarg** [comment]
I have compiled the code on RHEL-8.8. However, when I am trying to run using start_upf.sh script, It is pulling the docker image for air5005/upu instead of taking the compiled code and creating redhat image from it. Please let me know how can I run UPF on Redhat-8
