### ISSUE TITLE
AVX/AVX2 And Number Of Processor Cores

### ISSUE THREAD

**Issue by infinitydon** [5GOpenUPF/openupf#4]
Hi,

I will like to ask if it is possible to disable AVX/AVX2 support (or any other dependent processor feature) while building the container image?

Currently I have a server with SRIOV capable network cards but when I try to create the UPF-C, the k8s pod simply fails without any logs, so I am assuming that this is because the processor I am using does not support the AVX/AVX2 extensions (this is my guess because k8s did not show any logs at all).

I decided to start the POD with bash alone and then start the process manually, below is the error I got:

```
[root@upf-c-5k4wl upf]# echo $UPF_RUNCONFIG
/opt/upf/config/smu/smu_docker.ini
[root@upf-c-5k4wl upf]#
[root@upf-c-5k4wl upf]#
[root@upf-c-5k4wl upf]# /opt/upf/bin/smu
Illegal instruction (core dumped)
``` 

Also will it possible to deploy the UPF with just 8 cores? My hardware is Dell VEP 1445 and it only has 8 cores.

**Comment by 784432821** [comment]
Of course. Exist mainly DPDK use, according to different CPU architecture and instruction set only need to adjust the core/service/CMakeLists.txt in the instruction set
[https://github.com/5GOpenUPF/openupf/blob/master/core/service/CMakeLists.txt](url)
