### ISSUE TITLE
Do OpenUPF support ULCL? 

### ISSUE THREAD

**Issue by K-Nanako** [5GOpenUPF/openupf#5]
Hello,

I’m planning to use OpenUPF by docker.
Let me ask some questions related to ULCL.

Do OpenUPF support ULCL? If so, please let me know:
・How can I configure it?
・How many UPF do I have to deploy for ULCL? (for example, we need to prepare three UPFs for ULCL.)
・Can I deploy multiple OpenUPF on the same host machine?

I would appreciate it if you could tell me.
Thank you for your help.

**Comment by 784432821** [comment]
yes. To support ulcl, at least 3 sets of openupf are required, and the configuration file needs to be carefully modified, such as the IP address of N3 / N4 / N9 / N6 and the port number of openupf internal message channel.
If you want to deploy multiple sets of openupf on the same host, you may need to configure it correctly

**Comment by K-Nanako** [comment]
Thank you for your response.
I understand that these are available for use if I configure it correctly.

I appreciate your help.

**Comment by hrkgarg** [comment]
I have compiled the code on RHEL-8.8. However, when I am trying to run using start_upf.sh script, It is pulling the docker image for air5005/upu instead of taking the compiled code and creating redhat image from it. Please let me know how can I run UPF on Redhat-8
